Repository gardener/website-generator, pull requests merged in 2020-11, with the labels that each got.

#47 Change Packet brand to Equinix Metal
  hugo/layouts/index.html
  hugo/static/images/lp/platforms/equinix-metal.svg
Labels: component/documentation, needs/review, size/s

#59 Remove nodejs
  .ci/build
  .ci/gitlog.sh
  .ci/trigger_release
  Dockerfile
  hugo/layouts/partials/git_author.html
  node/generateVersioningFile.js
  node/index.js
  node/util/rewriteAbsoluteToUrls.js
  package-lock.json
  scripts/generateVersioningFile.py
Labels: needs/changes, needs/second-opinion, size/xl

#61 use remote template
  .ci/build
  Dockerfile
Labels: reviewed/lgtm, size/xs
