Repository gardener/website-generator, pull requests merged in 2020-06, with the labels that each got.

#21 Fix a typo
  README.md
Labels: reviewed/lgtm

#23 Fix usage of gardener.css in layouts
  hugo/layouts/partials/head-docs.html
  hugo/layouts/partials/header_blank.html
  hugo/layouts/partials/header_remote.html
Labels: area/documentation

#25 News and blogs
  hugo/assets/sass/_base.scss
  hugo/assets/sass/_blog.scss
  hugo/assets/sass/_news-feed.scss
  hugo/assets/sass/_news.scss
  hugo/layouts/blog/blog-list.html
  hugo/layouts/blog/list.html
  hugo/layouts/news/list.html
  hugo/layouts/news/single.html
  hugo/layouts/partials/footer.html
  hugo/layouts/partials/news.html
Labels: component/documentation

#26 News type
  hugo/assets/sass/_news-item.scss
  hugo/assets/sass/_news-releasenotes.scss
  hugo/assets/sass/_news.scss
  hugo/layouts/partials/news.html
Labels: component/documentation

#27 Blogs home page
  hugo/assets/sass/_blog-home.scss
  hugo/assets/sass/_blog.scss
  hugo/layouts/blog/blog-list.html
  hugo/layouts/partials/blog-authors.html
Labels: component/documentation

#28 Improved blog_img shortcode
  hugo/layouts/shortcodes/blog_img.html
Labels: component/documentation

#29 Blogs tag support
  hugo/assets/sass/_blog-home.scss
  hugo/layouts/blog/blog-list.html
  hugo/layouts/shortcodes/blog_img.html
Labels: component/documentation

#30 Preserve git info and history across renames/moves
  .ci/gitlog.sh
  node/index.js
Labels: component/documentation
