Repository gardener/website-generator, pull requests merged in 2021-02, with the labels that each got.

#64 Change image registry, upgrade docforge
  Dockerfile
Labels: needs/review, size/xs

#70 Upgrade hugo and docforge in gardener-website-generator image
  Dockerfile
Labels: needs/review, size/xs

#75 use rrobin fr github auth
  .ci/build
Labels: reviewed/lgtm, size/xs

#71 list controls as js lib
  hugo/layouts/docs/guides-home.html
  hugo/layouts/docs/tutorials-home.html
  hugo/static/js/dist/docs-guides-home.dev.js
  hugo/static/js/dist/docs-listpage.dev.js
  hugo/static/js/dist/docs-tutorials-home.dev.js
  hugo/static/js/docs-guides-home.js
  hugo/static/js/docs-listcontrol.js
  hugo/static/js/docs-listpage.js
  hugo/static/js/docs-tutorials-home.js
Labels: needs/review, needs/second-opinion, size/xl

#69 Cleanup unused layouts and partials
  hugo/layouts/blank/list.html
  hugo/layouts/blank/single.html
  hugo/layouts/components/list.html
  hugo/layouts/components/single.html
  hugo/layouts/contribute/list.html
  hugo/layouts/contribute/single.html
  hugo/layouts/installer/list.html
  hugo/layouts/installer/single.html
  hugo/layouts/kb/list.html
  hugo/layouts/kb/single.html
  hugo/layouts/kb/skill.html
  hugo/layouts/kb/topic.html
  hugo/layouts/landingpage/list.html
  hugo/layouts/news/list.html
  hugo/layouts/news/single.html
  hugo/layouts/padding/list.html
  hugo/layouts/padding/single.html
  hugo/layouts/partials/custom-footer.html
  hugo/layouts/partials/custom-header.html
  hugo/layouts/partials/footer-doc.html
  hugo/layouts/partials/footer_blank.html
  hugo/layouts/partials/head-docs.html
  hugo/layouts/partials/head-google-tag-manager.html
  hugo/layouts/partials/header_blank.html
  hugo/layouts/partials/header_local.html
  hugo/layouts/partials/header_remote.html
  hugo/layouts/partials/menu-footer.html
  hugo/layouts/partials/menu.html
  hugo/layouts/partials/toolbar.html
  hugo/layouts/tutorial-app/list.html
  hugo/layouts/tutorial-app/single.html
  hugo/layouts/tutorial-page/list.html
  hugo/layouts/tutorial-page/single.html
  hugo/layouts/tutorials/list.html
  hugo/layouts/tutorials/single.html
Labels: needs/review, needs/second-opinion, size/xl
