Repository gardener/website-generator, pull requests merged in 2021-07, with the labels that each got.

#82 [Docsy] Release new docforge
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#83 Update Hugo version
  Dockerfile
Labels: needs/review, size/xs

#84 Release website-generator
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#85 Install postcss-cli
  .ci/build
  Dockerfile
Labels: needs/review, size/xs

#86 Fix landing page when size is lower than 750px
  hugo/assets/sass/_landing-page.scss
  hugo/assets/sass/_news-feed.scss
  hugo/assets/sass/gardener.scss
  hugo/assets/scss/_blog-doc.scss
  hugo/assets/scss/_custom-search.scss
  hugo/layouts/index.html
  hugo/layouts/partials/navbar.html
Labels: needs/review, size/s

#87 Change min-size constants in the landing page
  hugo/assets/sass/_landing-page.scss
  hugo/assets/scss/_blog-doc.scss
Labels: needs/review, size/xs

#88 Fix news section
  hugo/assets/sass/_landing-page.scss
  hugo/assets/sass/_news-feed.scss
  hugo/assets/sass/gardener.scss
  hugo/assets/scss/_custom-grid.scss
  hugo/assets/scss/_styles_project.scss
  hugo/layouts/index.html
  hugo/layouts/partials/news.html
Labels: needs/review, size/m

#89 Fix community and adopters page on low resolution screens
  hugo/assets/sass/_community.scss
  hugo/assets/scss/_adopter.scss
Labels: needs/review, size/xs

#90 Add some padding in community page
  hugo/assets/sass/_community.scss
  hugo/assets/scss/_blog-doc.scss
Labels: needs/review, size/xs

#91 Update Community Meetings button
  hugo/layouts/community/list.html
Labels: reviewed/lgtm, size/xs

#93 Fix a typo (word repetition)
  hugo/layouts/index.html
Labels: reviewed/lgtm, size/xs
