Repository gardener/website-generator, pull requests merged in 2021-08, with the labels that each got.

#94 use gardener-website-generator:10.13.0
  .ci/pipeline_definitions
  Dockerfile
Labels: reviewed/lgtm, size/xs

#96 Release: use git handler
  .ci/build
  .ci/pipeline_definitions
  Dockerfile
Labels: reviewed/lgtm, size/xs

#97 Add debug string in build command
  .ci/build
Labels: needs/review, size/xs

#98 Fix git issue
  .ci/build
Labels: needs/review, size/xs

#99 Fixes for git
  .ci/build
Labels: needs/review

#100 Fixes for git handler
  .ci/build
Labels: needs/review

#101 Fixes for git
  .ci/build
Labels: needs/review, size/xs

#102 Remove debug messages
  .ci/build
Labels: needs/review

#104 Check if cache exists
  .ci/build
Labels: needs/review, size/xs

#105 Revert "Check if cache exists"
  .ci/build
Labels: needs/review, size/xs

#106 Install npm modules only if they are missing
  .ci/build
Labels: needs/review

#107 Fix modules installation
  .ci/build
Labels: needs/review
