Repository gardener/website-generator, pull requests merged in 2022-03, with the labels that each got.

#141 Use docforge:v0.25.0 & gardener-website-generator:10.28.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs

#142 Set docforge --cache-dir option
  .ci/build
Labels: needs/review, size/xs

#143 Updates package.json
  .gitignore
  hugo/assets/sass/_code-snippets.scss
  hugo/assets/sass/_code-style.scss
  hugo/hugo_stats.json
  hugo/layouts/partials/footer.html
  hugo/package-lock.json
  hugo/package.json
  hugo/postcss.config.js
Labels: needs/review, needs/second-opinion, size/xl

#146 Use docforge:v0.26.0 & gardener-website-generator:10.29.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs

#147 Use docforge:v0.27.0 & gardener-website-generator:10.30.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs

#148 Use docforge:v0.28.0 & gardener-website-generator:10.31.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs

#149 Make the Local build steps up to date
  README.md
Labels: needs/review, size/m

#151 Change the link from internal to external
  README.md
Labels: needs/review, size/xs

#152 Fix Github link
  README.md
Labels: needs/review, size/xs

#150 Updated list.html
  hugo/layouts/community/list.html
Labels: reviewed/lgtm, size/s

#154 Fix deprecated Page.URL in layouts
  Makefile
  hugo/assets/sass/_code-snippets.scss
  hugo/assets/sass/_code-style.scss
  hugo/layouts/partials/footer.html
Labels: needs/review, size/s

#153 Updated community images
  hugo/static/images/branding/slack-logo-green.svg
  hugo/static/images/branding/twitter-logo-green.svg
  hugo/static/images/branding/youtube-logo-green.svg
  hugo/static/images/lp/comms-community-meetings.svg
  images/overview.sketch
  images/overview.svg
Labels: needs/review, needs/second-opinion, size/xl

#155 Updates npm dependencies and fix shell check issues
  .ci/build
  .ci/component_descriptor
  .ci/set_dependency_version
  .gitignore
  hugo/hugo_stats.json
  hugo/package-lock.json
  hugo/package.json
  hugo/postcss.config.js
  package-lock.json
Labels: needs/review, needs/second-opinion, size/xl

#157 Update npm dependencies and fix shell check issues
  .ci/build
  .ci/component_descriptor
  .ci/set_dependency_version
  .gitignore
  hugo/hugo_stats.json
  hugo/package-lock.json
  hugo/package.json
  hugo/postcss.config.js
  package-lock.json
  scripts/image-build
  scripts/image-push
  scripts/image-stable
  scripts/mklink.sh
  scripts/setup
Labels: needs/review, needs/second-opinion, size/xl

#158 Use docforge:v0.29.0 & gardener-website-generator:10.32.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs

#159 Use docforge:v0.30.0 & gardener-website-generator:10.33.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs
