Repository gardener/website-generator, pull requests merged in 2022-08, with the labels that each got.

#171 News redirect
  hugo/layouts/partials/news.html
Labels: needs/review, size/s

#172 Build script refactoring
  .ci/build
  .ci/pipeline_definitions
Labels: needs/review, size/m

#173 News upper limit
  hugo/layouts/partials/news.html
Labels: needs/review, size/xs

#174 Community table fix
  hugo/layouts/community/list.html
Labels: needs/review, size/xs

#175 Showing only unarchived blogs
  hugo/layouts/blog/list.html
  hugo/layouts/partials/sidebar-tree.html
Labels: needs/review, size/s

#176 Removing docker build issue workaround
  scripts/image-build
Labels: reviewed/lgtm, size/xs

#177 Use docforge:v0.32.0 & gardener-website-generator:10.35.0 images
  .ci/pipeline_definitions
  Dockerfile
Labels: needs/review, size/xs
