Repository gardener/website-generator, pull requests merged in 2024-12, with the labels that each got.

#240 [Docker] Running web server using docker compose
  Dockerfile
  README.md
  compose.yaml
  hugo/config.toml
Labels: reviewed/lgtm, size/s

#242 [Docker] Move `DOCFORGE_CONFIG` in compose instead of image
  Dockerfile
  compose.yaml
Labels: reviewed/lgtm, size/xs

#244 [Docker] Setup `docsy@DOCSY_VERSION` under `hugo/themes` on image build
  Dockerfile
Labels: needs/review, size/xs

#245 [Docker] Add `BUILD_DESTINATION`
  Dockerfile
Labels: needs/review, size/xs

#246 [Docker] Add `DOCFORGE_CONFIG_PATH`
  Dockerfile
Labels: needs/review, size/xs

#243 [Docker] support local dev
  README.md
Labels: needs/review, size/xs

#247 Rename to WEBSITE_BUILD_PATH
  Dockerfile
Labels: needs/review, reviewed/lgtm, size/xs

#248 Dockerfile uses docforge v0.50
  Dockerfile
Labels: needs/review, reviewed/lgtm, size/xs

#249 Updated copyright for 2025
  hugo/config.toml
Labels: reviewed/lgtm, size/xs
