Repository gardener/website-generator, pull requests merged in 2024-07, with the labels that each got.

#215 Updated "404 Page Not Found" page layout
  .ci/404.sh
  hugo/layouts/404.html
Labels: reviewed/lgtm, size/xs

#216 Add special handling for diki report docu in build script
  .ci/build
Labels: needs/review, reviewed/lgtm, size/xs

#217 Fix diki hardened-shoot report docu styles
  .ci/build
Labels: needs/review, reviewed/lgtm, size/xs

#218 Use docforge v0.46
  .ci/build
  .ci/pipeline_definitions
  Dockerfile
  Makefile
Labels: reviewed/lgtm, size/xs

#219 Fixed links in Page Not Found page
  .ci/404.sh
Labels: reviewed/lgtm, size/xs

#220 Drop component descriptor
  .ci/component_descriptor
  .ci/pipeline_definitions
Labels: needs/review, size/xs

#221 Migrate remaining GCR occurrences to GAR
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  scripts/image-build
  scripts/image-push
  scripts/image-stable
Labels: needs/review, size/s
