Repository gardener/website-generator, pull requests merged in 2024-11, with the labels that each got.

#229 Update pipeline definitions and configurations after `Hugo` and `Docsy` update
  .ci/pipeline_definitions
  hugo/config.toml
  hugo/layouts/partials/docs/section-index.html
Labels: needs/review, size/xs

#231 Add and support for website image
  .ci/pipeline_definitions
  scripts/image-build
Labels: reviewed/lgtm, size/xs

#232 Update npm install directory
  .ci/build
Labels: reviewed/lgtm, size/xs

#233 Add npm install in Hugo directory
  .ci/build
Labels: reviewed/lgtm, size/xs

#230 Add support for Github notes syntax
  hugo/layouts/_default/_markup/render-blockquote-alert.html
  hugo/layouts/_default/_markup/render-blockquote-regular.html
  hugo/layouts/partials/navbar.html
Labels: reviewed/lgtm, size/s

#234 Update setup documentation
  README.md
Labels: reviewed/lgtm, size/xs

#235 Fix landing page
  hugo/assets/sass/_landing-page.scss
Labels: reviewed/lgtm, size/xs

#237 Improve blockquote alerts
  README.md
  hugo/assets/sass/_base.scss
  hugo/layouts/_default/_markup/render-blockquote-alert.html
  hugo/package-lock.json
Labels: reviewed/lgtm, size/xl
