Repository gardener/website-generator, pull requests merged in 2025-02, with the labels that each got.

#258 Add release job
  .ci/pipeline_definitions
Labels: needs/review, size/xs, ci/broken-pipeline-definition

#259 Use `Dockerfile` from docker branch
  Dockerfile
  package.json
Labels: needs/review, size/s

#260 Update `Hugo` and `Docforge` versions
  Dockerfile
Labels: reviewed/lgtm, size/xs

#263 Cleanup unused layouts
  hugo/layouts/.nojekyll
  hugo/layouts/docs/list.html
Labels: needs/review, size/xs

#264 Revert removal of docs/list.html layout
  hugo/layouts/docs/list.html
Labels: needs/review, size/xs

#265 Fix cosmetic bugs
  hugo/assets/sass/_base.scss
  hugo/assets/sass/_code-snippets.scss
  hugo/layouts/community/list.html
  hugo/layouts/docs/baseof.html
  hugo/static/css/font-awesome.css
  hugo/static/fonts/fontawesome/fontawesome-webfont.woff2
Labels: reviewed/lgtm, size/xl

#266 Add heading self links and anchors
  hugo/assets/js/anchor.js
  hugo/layouts/_default/_markup/render-heading.html
Labels: needs/review, reviewed/lgtm, size/s

#270 Add community list.html
  hugo/layouts/community/list.html
Labels: reviewed/lgtm, size/xs

#267 Added Statements to Landing Page
  hugo/config.toml
  hugo/layouts/partials/footer.html
Labels: reviewed/lgtm, size/xs

#269 Fix navbar cutting off sidebars
  hugo/assets/sass/_base.scss
Labels: reviewed/lgtm, size/xs
