Repository gardener/website-generator, pull requests merged in 2025-04, with the labels that each got.

#287 Added button for joining the Slack community
  hugo/assets/sass/_base.scss
  hugo/config.toml
  hugo/layouts/partials/navbar.html
  hugo/static/images/branding/slack-icon.svg
Labels: needs/review, reviewed/lgtm, size/m

#286 Switch Slack references to Gardener workspace
  hugo/layouts/partials/footer.html
Labels: area/open-source, kind/enhancement, needs/review, size/xs

#289 Revert "Add openMCP for KubeCon in community bio page"
  hugo/layouts/shortcodes/community-bio.html
  hugo/static/images/community/mcp_gardener.png
Labels: needs/review, size/xs

#288 Deep cleanup of website
  hugo/assets/sass/_base.scss
  hugo/assets/sass/tutorials.scss
  hugo/assets/scss/_selected-taxonomy.scss
  hugo/config.toml
  hugo/layouts/blog/baseof.html
  hugo/layouts/community/baseof.html
  hugo/layouts/community/list.html
  hugo/layouts/docs/baseof.html
  hugo/layouts/docs/list.html
  hugo/layouts/index.html
  hugo/layouts/partials/category_map.html
  hugo/layouts/partials/docs/git_author.html
  hugo/layouts/partials/docs/git_resource_path.html
  hugo/layouts/partials/docs/page-meta-links.html
  hugo/layouts/partials/docs/section-index-element.html
  hugo/layouts/partials/docs/section-index.html
  hugo/layouts/partials/google-tags-manager-frame.html
  hugo/layouts/partials/google-tags-manager.html
  hugo/layouts/partials/hooks/body-end.html
  hugo/layouts/partials/navbar.html
  hugo/layouts/partials/news.html
  hugo/layouts/partials/sidebar-tree.html
  hugo/layouts/shortcodes/community-bio.html
  hugo/static/images/footer-green-light.svg
  hugo/static/images/footer-green-sharp.svg
  hugo/static/images/lp/lp-header-green-1.svg
  hugo/static/images/lp/lp-header-green-2.svg
  hugo/static/images/lp/lp-header-green-3.svg
  hugo/static/images/lp/lp-header-green-4.svg
  hugo/static/images/lp/lp-header-green-5.svg
  hugo/static/images/lp/lp-header-green-6.svg
  hugo/static/images/lp/lp-header-green-7.svg
  hugo/static/images/lp/lp-header-green-9.svg
  hugo/static/images/lp/lp-header-green.svg
  hugo/static/js/filtering.js
  hugo/static/js/main.js
  hugo/static/js/navbar.js
  hugo/static/js/page-content.js
  hugo/static/js/persona-filtering.js
Labels: reviewed/lgtm, size/xl
